### ISSUE TITLE
[Bug]: selenium.common.exceptions.JavascriptException: Message: javascript error: point.offset is not a function

### ISSUE THREAD

**Issue by vvatelot** [cnumr/ecoindex_python#33]
### What happened?

Issue appears when calling
```
asyncio.run(get_page_analysis(url="https://www.patoutrailsaintlary.com"))
```

### Version

^3.6

### What OS do you use?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    result = asyncio.run(get_page_analysis(url="https://www.patoutrailsaintlary.com"))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/20100229/Devel/ecoindex_python/ecoindex/scrap.py", line 23, in get_page_analysis
    page_metrics, page_type = await scrap_page(
  File "/home/20100229/Devel/ecoindex_python/ecoindex/scrap.py", line 67, in scrap_page
    driver.execute_script(
  File "/home/20100229/.cache/pypoetry/virtualenvs/ecoindex-algVPkgo-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 790, in execute_script
    return self.execute(command, {
  File "/home/20100229/.cache/pypoetry/virtualenvs/ecoindex-algVPkgo-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "/home/20100229/.cache/pypoetry/virtualenvs/ecoindex-algVPkgo-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: point.offset is not a function
  (Session info: chrome=95.0.4638.69)
Stacktrace:
#0 0x55fc9fd00f93 <unknown>
#1 0x55fc9f7db908 <unknown>
#2 0x55fc9f7de78c <unknown>
#3 0x55fc9f7de586 <unknown>
#4 0x55fc9f7df142 <unknown>
#5 0x55fc9f842983 <unknown>
#6 0x55fc9f82ea82 <unknown>
#7 0x55fc9f841c91 <unknown>
#8 0x55fc9f82e973 <unknown>
#9 0x55fc9f804df4 <unknown>
#10 0x55fc9f805de5 <unknown>
#11 0x55fc9fd302be <unknown>
#12 0x55fc9fd45ba0 <unknown>
#13 0x55fc9fd31215 <unknown>
#14 0x55fc9fd46fe8 <unknown>
#15 0x55fc9fd259db <unknown>
#16 0x55fc9fd62218 <unknown>
#17 0x55fc9fd62398 <unknown>
#18 0x55fc9fd7d6cd <unknown>
#19 0x7f3870da4609 <unknown>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Relates https://github.com/cnumr/ecoindex_cli/pull/83

**Comment by vvatelot** [comment]
Seems related to the javascript action to scroll to the bottom of the page:
```
"window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' })"
```

**Comment by vvatelot** [comment]
@mikefromlig for the explanation: The website patoutrailsaintlary.com overloaded the javascript function `scrollTo` that I use in the page scraper to simulate a scroll to bottom action. So, as it was overloaded, it returned a javascript exception which is not relevant in our case.
